server:
  port: 8080
spring:
  main:
    banner-mode: "off"
  application:
    name: project-template
  datasource:
    url: jdbc:mysql://192.168.136.128:30001/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: demo
    password: demo123
  jpa:
    mysql:
      packagesToScan:
        - apps.example.*
  kafka:
    bootstrapServers:
      - 192.168.136.128:30004
    dispatcher:
      enable: true
      topics:
        - example