server:
  port: 8080
spring:
  application:
    name: alerting-service
  kafka:
    consumer:
      bootstrapServers:
        - 192.168.136.128:30004
    listener:
      type: BATCH
      ackMode: MANUAL_IMMEDIATE
      concurrency: 2
