name: framework-parent

on:
  push:
    branches: [ "main" ]
    paths:
      - 'core-parent/**'
      - '.github/workflows/core-parent.yml'

env:
  GITHUB_ACTOR: fvxiaoyi
  GITHUB_TOKEN: ${{ secrets.MAVEN_SERVER_TOKEN }}

jobs:
  call-workflow:
    uses: ./.github/workflows/maven-build.yml
    with:
      work-dir: core-parent