name: framework-parent

on:
  push:
    branches: [ "main" ]
    paths:
      - 'core-parent/**'
      - '.github/workflows/core-parent.yml'

jobs:
  call-workflow:
    uses: ./.github/workflows/maven-build.yml
    with:
      work-dir: core-parent
    secrets: inherit