name: build ebin-core

on:
  push:
    branches: [ "main" ]
    paths:
      - 'core-parent/**'
      - 'core-modules/**'
      - '.github/workflows/core-parent.yml'

jobs:
  build-parent:
    uses: ./.github/workflows/maven-build.yml
    with:
      work-dir: core-parent
      jdk: 16.0.2+7
    secrets: inherit
  build-modules:
    uses: ./.github/workflows/maven-build.yml
    with:
      work-dir: core-modules
      jdk: 16.0.2+7
    secrets: inherit