name: build ddd-check-style-additional-plugin

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/ddd-checkstyle-additional-plugin/**'
      - '.github/workflows/ddd-check-style-additional-plugin.yml'

jobs:
  build-plugin:
    uses: ./.github/workflows/maven-build.yml
    with:
      work-dir: tools/ddd-checkstyle-additional-plugin
      jdk: 11
    secrets: inherit