name: framework-core

on:
  push:
    branches: [ "main" ]
    paths:
      - 'framework-core/**'
      - '.github/workflows/framework-core.yml'
      
env:
  WORK_DIR: framework-core

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: x
      run: cat /home/runner/.m2/settings.xml
    - uses: s4u/maven-settings-action@v2.6.0
      with:
        githubServer: false
        servers: |
          [{
              "id": "github",
              "username": "fvxiaoyi",
              "password": "${{ secrets.MAVEN_SERVER_TOKEN }}"
          }]
    - name: x1
      run: cat /home/runner/.m2/settings.xml
    - name: Build with Maven
      run: |
        cd ${{ env.WORK_DIR }}
        mvn deploy
