name: framework-core

on:
  push:
    branches: [ "main" ]
    paths:
      - 'framework-core-domain/**'
      - '.github/workflows/framework-core-domain.yml'
      
env:
  WORK_DIR: framework-core
  GITHUB_ACTOR: fvxiaoyi
  GITHUB_TOKEN: ${{ secrets.MAVEN_SERVER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd ${{ env.WORK_DIR }}
        mvn deploy
