name: spring-docker-package-maven-plugin

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/spring-docker-package-maven-plugin/**'
      - '.github/workflows/spring-docker-package-maven-plugin.yml'
      
env:
  WORK_DIR: tools/spring-docker-package-maven-plugin
  GITHUB_ACTOR: fvxiaoyi
  GITHUB_TOKEN: ${{ secrets.MAVEN_SERVER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd ${{ env.WORK_DIR }}
        mvn deploy
