name: build spring-docker-package-maven-plugin

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/spring-docker-package-maven-plugin/**'
      - '.github/workflows/spring-docker-package-maven-plugin.yml'

jobs:
  build-modules:
    uses: ./.github/workflows/maven-build.yml
    with:
      work-dir: tools/spring-docker-package-maven-plugin
      jdk: 11
    secrets: inherit